name: Gh-Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Only works with v2
      - uses: subosito/flutter-action@v2.4.0
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          webRenderer: canvaskit
